version: '3'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: socialspace
      MYSQL_DATABASE: socialspace
      MYSQL_USER: socialspace
      MYSQL_PASSWORD: socialspace
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 450M

  app:
    image: msarmadqadeer/socialspace:latest
    container_name: app
    depends_on:
      - mysql
    restart: always
    # command: bash -c "php artisan serve --host=0.0.0.0 --port=8181"
    command: bash -c "php artisan migrate && php artisan db:seed && php artisan serve --host=0.0.0.0 --port=80"
    ports:
      - "8082:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 200M
